require 'rspec/core/rake_task'
require 'mno_enterprise/testing_support/common_rake'

Bundler::GemHelper.install_tasks
RSpec::Core::RakeTask.new

task default: :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'mno_enterprise/frontend'
  Rake::Task['mno_enterprise:testing:create_dummy_app'].invoke
end
