eval(File.read(File.dirname(__FILE__) + '/../common_mnoe_dependencies.rb'))

# Declare your gem's dependencies in mno_enterprise.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.
group :test, :development do
  # Email
  gem 'mandrill-api', '~> 1.0.53'
  gem 'sparkpost', '~> 0.1.4'
end


# To use a debugger
# gem 'byebug', group: [:development, :test]
