begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'rdoc/task'

APP_RAKEFILE = File.expand_path("../spec/dummy/Rakefile", __FILE__)

if File.exists?(APP_RAKEFILE)
  load 'rails/tasks/engine.rake'
end

Bundler::GemHelper.install_tasks

# require 'rake/testtask'

# Rake::TestTask.new(:spec) do |t|
#   t.libs << 'lib'
#   t.libs << 'spec'
#   t.pattern = 'spec/**/*_spec.rb'
#   t.verbose = false
# end

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new

# desc "Run specs"
# RSpec::Core::RakeTask.new do |t|
#   t.pattern = "./*/spec/**/*_spec.rb"
# end

# task :spec

task default: :spec

# desc "Generates a dummy app for testing"
# task :test_app do
#   ENV['LIB_NAME'] = 'maestrano_enterprise/core'
#   Rake::Task['common:test_app'].invoke
# end

require 'mno_enterprise/testing_support/common_rake'

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'mno_enterprise/core'
  Rake::Task['mno_enterprise:testing:create_dummy_app'].invoke
end
