json.id subscription_event.id
json.event_type subscription_event.event_type
json.status subscription_event.status
json.message subscription_event.message
json.provisioning_data subscription_event.provisioning_data
json.created_at subscription_event.created_at
json.updated_at subscription_event.updated_at
