source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 4.2.6'

# Use Puma as the app server
gem 'puma', '~> 3.0'

<% gemfile_entries.each do |gem| -%>

<% if gem.comment -%>
# <%= gem.comment %>
<% end -%>
<%= gem.commented_out ? '# ' : '' %>gem '<%= gem.name %>'<%= %(, '#{gem.version}') if gem.version -%>
<% if gem.options.any? -%>
, <%= gem.options.map { |k,v|
  "#{k}: #{v.inspect}" }.join(', ') %>
<% end -%>
<% end -%>

# Ops gems
group :uat, :production do
  gem 'newrelic_rpm'
end

# CI gems
group :development do
  # Security audits
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false

  # Style check
  gem 'rubocop', '~> 0.46', require: false
  gem 'rubocop-rspec', '~> 1.8.0', require: false
end

group :development, :test do
<%- if spring_install? %>
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-commands-rspec'
<% end -%>
  gem 'figaro'
end

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'

  # Code coverage
  gem 'simplecov'
end
